export const sx = {
  sectionHeader:   { display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 1.5, mb: 3 },
  sectionTitle:    { fontSize: 15, fontWeight: 600, color: "var(--text)", fontFamily: "'DM Sans', sans-serif" },
  sectionSubtitle: { fontSize: 11, fontWeight: 600, color: "var(--text3)", fontFamily: "'DM Sans', sans-serif", textTransform: "uppercase", letterSpacing: "0.08em", mb: 2 },
  divider:         { borderColor: "var(--border)", my: 3 },
  btnRow:          { display: "flex", gap: 1 },
  fieldGrid:       { display: "grid", gridTemplateColumns: { xs: "1fr", md: "repeat(3, 1fr)" }, gap: 2.5 },
  fieldGroup:      {},
  fieldLabel:      { fontSize: 11, fontWeight: 600, color: "var(--text3)", fontFamily: "'DM Sans', sans-serif", textTransform: "uppercase", letterSpacing: "0.06em", mb: 0.5 },
  fieldValue:      { fontSize: 13, color: "var(--text)", fontFamily: "'DM Sans', sans-serif" },
  textField: {
    "& .MuiOutlinedInput-root": {
      color: "var(--text)", fontSize: 13, fontFamily: "'DM Sans', sans-serif", background: "var(--surface2)",
      "& fieldset": { borderColor: "var(--border)" },
      "&:hover fieldset": { borderColor: "var(--border2)" },
      "&.Mui-focused fieldset": { borderColor: "var(--accent)" },
    },
  },
  selectField: {
    color: "var(--text)", fontSize: 13, fontFamily: "'DM Sans', sans-serif", background: "var(--surface2)",
    "& .MuiOutlinedInput-notchedOutline": { borderColor: "var(--border)" },
    "&:hover .MuiOutlinedInput-notchedOutline": { borderColor: "var(--border2)" },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": { borderColor: "var(--accent)" },
    "& .MuiSvgIcon-root": { color: "var(--text3)" },
  },
  menuProps: {
    PaperProps: {
      sx: {
        background: "var(--surface2)", border: "1px solid var(--border)", borderRadius: "6px",
        "& .MuiMenuItem-root": { color: "var(--text)", fontSize: 13, fontFamily: "'DM Sans', sans-serif" },
        "& .MuiMenuItem-root:hover": { background: "var(--surface3)" },
        "& .MuiMenuItem-root.Mui-selected": { background: "var(--surface3)", color: "var(--accent)" },
      },
    },
  },
  menuItem:  { color: "var(--text)", fontSize: 13, fontFamily: "'DM Sans', sans-serif" },
  editBtn:   { color: "var(--accent)", fontSize: 12, fontFamily: "'DM Sans', sans-serif", textTransform: "none", border: "1px solid var(--accent-border)", borderRadius: "6px", px: 1.5, py: 0.5, "&:hover": { background: "var(--accent-soft)", borderColor: "var(--accent)" } },
  saveBtn:   { color: "var(--text-on-accent)", background: "var(--accent)", fontSize: 12, fontFamily: "'DM Sans', sans-serif", textTransform: "none", borderRadius: "6px", px: 2, py: 0.5, fontWeight: 600, "&:hover": { background: "var(--accent-hover)" }, "&.Mui-disabled": { background: "var(--disabled-bg)", color: "var(--text3)" } },
  cancelBtn: { color: "var(--text2)", fontSize: 12, fontFamily: "'DM Sans', sans-serif", textTransform: "none", borderRadius: "6px", px: 1.5, py: 0.5, "&:hover": { background: "var(--surface2)" } },
  dialogPaper:   { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "10px", minWidth: 360 },
  dialogTitle:   { color: "var(--text)", fontFamily: "'DM Sans', sans-serif", fontSize: 15, fontWeight: 600, pb: 1 },
  dialogContent: { pt: 0 },
  dialogBody:    { color: "var(--text2)", fontFamily: "'DM Sans', sans-serif", fontSize: 13 },
  dialogEmail:   { color: "var(--accent)", fontFamily: "'DM Sans', sans-serif", fontSize: 13, fontWeight: 600, mt: 1 },
  dialogActions: { px: 3, pb: 2, gap: 1 },
};
