export const sx = {
  root: { background: "var(--bg)", color: "var(--text)", minHeight: "100vh" },
  header: {
    px: { xs: 2, md: 3 },
    pt: { xs: 2, md: 3 },
    pb: 1.5,
    borderBottom: "1px solid var(--border)",
    background: "var(--surface)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 2,
    flexWrap: "wrap",
  },
  title: {
    fontSize: { xs: 17, md: 20 },
    fontWeight: 700,
    color: "var(--text)",
    fontFamily: "'Syne', sans-serif",
  },
  titleAccent: { color: "var(--accent)" },
  subtitle: {
    fontSize: 12,
    color: "var(--text3)",
    fontFamily: "'DM Sans', sans-serif",
    mt: 0.25,
  },
  nav: {
    display: "flex",
    gap: 1,
    background: "var(--surface2)",
    border: "1px solid var(--border)",
    borderRadius: "8px",
    p: 0.5,
  },
  navBtn: (active) => ({
    color: active ? "var(--text-on-accent)" : "var(--text2)",
    background: active ? "var(--accent)" : "transparent",
    fontSize: 12,
    fontFamily: "'DM Sans', sans-serif",
    textTransform: "none",
    borderRadius: "6px",
    px: 1.5,
    py: 0.5,
    fontWeight: 600,
    minWidth: 0,
    "&:hover": {
      background: active ? "var(--accent-hover)" : "var(--surface3)",
      color: active ? "var(--text-on-accent)" : "var(--text)",
    },
  }),
};
