export const sx = {
  wrapper: { p: { xs: 2, md: 3 }, background: "var(--bg)", minHeight: "100vh" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 1.5,
    mb: 3,
  },
  title: {
    color: "var(--text)",
    fontSize: 22,
    fontWeight: 700,
    fontFamily: "'Syne', sans-serif",
  },
  meta: {
    color: "var(--text3)",
    fontSize: 12,
    fontFamily: "'DM Sans', sans-serif",
    mt: 0.25,
  },
  section: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "8px",
    p: 2.5,
    boxShadow: "var(--shadow)",
  },
  sectionTitle: {
    color: "var(--text)",
    fontSize: 15,
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    mb: 2,
  },
  themeGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "repeat(2, minmax(0, 1fr))" },
    gap: 2,
  },
  themeCard: (active) => ({
    appearance: "none",
    width: "100%",
    textAlign: "left",
    background: active ? "var(--accent-soft)" : "var(--surface2)",
    border: `1px solid ${active ? "var(--accent)" : "var(--border)"}`,
    borderRadius: "8px",
    p: 2,
    cursor: "pointer",
    transition: "border-color 0.15s, background 0.15s, transform 0.15s",
    "&:hover": {
      background: active ? "var(--accent-soft)" : "var(--surface3)",
      borderColor: active ? "var(--accent)" : "var(--border2)",
    },
    "&:focus-visible": {
      outline: "2px solid var(--accent)",
      outlineOffset: "2px",
    },
  }),
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 1.5,
    mb: 1.5,
  },
  themeName: {
    color: "var(--text)",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "'DM Sans', sans-serif",
  },
  themeDescription: {
    color: "var(--text3)",
    fontSize: 12,
    fontFamily: "'DM Sans', sans-serif",
    mt: 0.25,
  },
  selectedBadge: {
    color: "var(--text-on-accent)",
    background: "var(--accent)",
    borderRadius: "6px",
    px: 1,
    py: 0.35,
    fontSize: 11,
    fontWeight: 700,
    fontFamily: "'DM Sans', sans-serif",
    whiteSpace: "nowrap",
  },
  swatchRow: {
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
    gap: 0.75,
    mb: 1.5,
  },
  swatch: (color) => ({
    background: color,
    border: "1px solid var(--border)",
    borderRadius: "6px",
    height: 26,
  }),
  preview: (vars) => ({
    ...vars,
    background: "var(--bg)",
    border: "1px solid var(--border)",
    borderRadius: "8px",
    p: 1,
  }),
  previewBar: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "6px",
    height: 24,
    mb: 1,
    display: "flex",
    alignItems: "center",
    gap: 0.75,
    px: 0.75,
  },
  previewDot: (color) => ({
    background: color,
    borderRadius: "999px",
    height: 8,
    width: 8,
  }),
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "1.2fr 0.8fr",
    gap: 1,
  },
  previewPanel: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "6px",
    p: 1,
  },
  previewLine: (wide) => ({
    background: wide ? "var(--text2)" : "var(--text3)",
    borderRadius: "999px",
    height: 7,
    width: wide ? "80%" : "56%",
    mb: 0.75,
    opacity: 0.75,
  }),
  previewButton: {
    background: "var(--accent)",
    borderRadius: "5px",
    height: 12,
    width: 48,
  },
  backBtn: {
    color: "var(--accent)",
    fontSize: 12,
    fontFamily: "'DM Sans', sans-serif",
    textTransform: "none",
    border: "1px solid var(--accent-border)",
    borderRadius: "6px",
    px: 1.5,
    py: 0.5,
    "&:hover": {
      background: "var(--accent-soft)",
      borderColor: "var(--accent)",
    },
  },
};
